sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1224
  alioss:
    bucket-name: wangyoupeng-penghong
    access-key-secret: EJ5hJmjpHo926e7Mlugi3RAsB1AZ6S
    access-key-id: LTAI5tRRZNLER1ze1BpjWzPU
    endpoint: oss-cn-beijing.aliyuncs.com
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wx9d12f0b1b2c48ed2
    secret: 0823c82249aa9b9e28b822524a882e74
